config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers
  devise_for :customers, :controllers => { registrations: 'registrations' }
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "products#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :find_product, only: [:show]

	def index
		@products = Product.all
	end

	def show
		@category = Category.all
	end

	private
		def find_product
			@product = Product.find(params[:id])
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:customer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:customer).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>     
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>  
    <div class="col-md-10 col-md-offset-1">
	  <%= yield %>
	</div>
  </body>
</html>

app/views/products/index.html.erb
<h1> Index </h1>
<% @products.each do |product| %>
	<h1><%= link_to product.name, product %></h1>
<% end %>

<%= link_to "Register", new_customer_registration_path %>
<%= link_to "log out", destroy_customer_session_path, method: :delete%>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h5 style="background-color: #grey; color: red;"><%= %></h5>
<h4><%= @product.price %>$</h4>
<p><%= @product.description %></p>
<%= link_to "Go Back", root_path %>
<%= image_tag(@product.image_url, class: "show-image-lg")%>
<h6 style="color: red;">category: <%= @category.find(@product.category_id).name %></h6>